# Generated by Django 5.0.7 on 2024-08-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investidores', '0002_propostainvestimento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostainvestimento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
